# Generated by Django 3.1.3 on 2021-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_newsletter_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='support_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='0 expert, 5 débutant'),
        ),
    ]
