# Generated by Django 3.1.3 on 2021-01-15 15:19

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_summernote.fields.SummernoteTextField(verbose_name='Contenu'),
        ),
    ]
