# Generated by Django 3.1.3 on 2021-01-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20210113_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='tags',
            field=models.ManyToManyField(blank=True, to='calls.CallTag', verbose_name='Tags'),
        ),
    ]
