# Generated by Django 3.1.3 on 2021-01-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20210113_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.callcategory', verbose_name='Catégorie'),
        ),
    ]
