# Generated by Django 3.1.3 on 2021-01-14 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_call_call_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
