# Generated by Django 3.1.3 on 2021-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_call_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='solved_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de résolution'),
        ),
    ]
